### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by islishude** [islishude/web3-cli#4]
# documentation

- [x] how does it work?
- [x] how to import abi from local file system and remote http server
- [x] what's the abi decode rule (especially tuple and slice)
- [x] how to add a new chain configuration
- [x] how to use web3-cli in docker

# features

- [ ] detected if the contract is a proxy (e.g. uups/transparent/beacon)
- [x] add more builtin chains and abi
